version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASS}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - knights-data:/var/lib/postgresql/data

  node-app:
    image: calebgisa72/caleb-knights-be:v1.2
    container_name: backend
    env_file:
      - ./.env
    ports:
      - ${BE_PORT}:${BE_PORT}
    depends_on:
      - postgresdb

  knights-frontend:
    image: calebgisa72/caleb-knights-fe:v1.0
    container_name: frontend
    env_file:
      - ./.env
    ports:
      - 5000:5000
    depends_on:
      - node-app

volumes:
  knights-data:
